name: workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - openmm=7.7.0
  - jupyter
  - tqdm
  - mdtraj
  - seaborn
  - scikit-learn
  - cython
  - pip=22.3.1
  - pip:
    - crossflow==0.1.1
